# Generated by Django 5.2.5 on 2025-08-17 07:43

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='listings.listing'),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='listing_image'),
        ),
    ]
