# Generated by Django 5.2.4 on 2025-08-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
