# Generated by Django 5.2.5 on 2025-08-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_populate_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
