# Generated by Django 5.2.5 on 2025-08-17 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
