# Generated by Django 5.2.4 on 2025-08-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='full_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='shipping_address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='shipping_city',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='shipping_postal_code',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
