# Generated by Django 5.2.5 on 2025-08-22 15:54

from django.db import migrations


def populate_product_title(apps, schema_editor):
    """
    Populate the new product_title field with the title from the related listing
    for all existing OrderItems.
    """
    OrderItem = apps.get_model('listings', 'OrderItem')
    # Use an empty string for the title if the listing has been deleted
    DEFAULT_TITLE = '[Listing Removed]'

    # Select items that need updating and have a related listing
    items_to_update = OrderItem.objects.filter(product_title__isnull=True, listing__isnull=False)

    for item in items_to_update.select_related('listing'):
        item.product_title = item.listing.title
        item.save(update_fields=['product_title'])

    # Handle any orphaned items (listing was deleted)
    OrderItem.objects.filter(product_title__isnull=True).update(product_title=DEFAULT_TITLE)


class Migration(migrations.Migration):
    dependencies = [
        ('listings', '0004_orderitem_product_title_alter_order_total_price'),  # Replace with the name of your previous migration
    ]

    operations = [
        migrations.RunPython(populate_product_title, migrations.RunPython.noop),
    ]