# Generated by Django 5.2.4 on 2025-08-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_checkout_full_name_checkout_shipping_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
