# Generated by Django 5.2.5 on 2025-08-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_populate_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_title',
            field=models.CharField(max_length=200),
        ),
    ]
