# Generated by Django 5.2.4 on 2025-08-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_checkout_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkout',
            name='payment_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
