# Generated by Django 5.2.4 on 2025-08-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_checkout_paid_checkout_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='gift_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
