# Generated by Django 5.2.5 on 2025-08-22 17:38

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='avatar')),
                ('bio', models.TextField(blank=True)),
                ('credit_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('phone', models.CharField(blank=True, help_text='Enter your 10-digit PH mobile number (e.g., 9171234567).', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits, e.g., 9171234567.', regex='^\\d{10}$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
