# Generated by Django 5.2.5 on 2025-08-22 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('listings', '0007_alter_review_unique_together_order_credit_used_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistoryView',
            fields=[
                ('listing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.listing')),
            ],
            bases=('listings.listing',),
        ),
    ]
