# Generated by Django 5.2.5 on 2025-08-20 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, help_text='Enter your 10-digit PH mobile number (e.g., 9171234567).', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits, e.g., 9171234567.', regex='^\\d{10}$')]),
        ),
    ]
